server:
  port: 80
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mycnblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      username: root
      password: RLFrlf930Frank_wjq


mybatis-plus:
  global-config:
    db-config:
      table-prefix:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/**Mapper.xml

logging:
  file:
    path: ./src/main/java/com/example/ademo/log
    name:
  level:
    root: info
    com:
      example:
        ademo:
          controller: debug
          mapper: debug

